[package]
name = "moonmonet-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.104"
monet-rs = { path = "../monetwannabe-rs-new" }
